use some_db;

CREATE TABLE SAMPLE (
	ID INT NOT NULL,
	NAME varchar(100) NULL,
	DESCRIPTION varchar(100) NULL,
	CONSTRAINT SAMPE_PK PRIMARY KEY (ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE INVOICE (
	ID INT NOT NULL,
	NAME varchar(100) NULL,	
	DESCRIPTION varchar(100) NULL,
	CONSTRAINT INVOICE_PK PRIMARY KEY (ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE INVOICE_DETAIL (
	ID INT NOT NULL,
	INVOICE_ID INT NOT NULL,
	QTD INT NOT NULL,
	PRICE DECIMAL(10, 2) NOT NULL,
	DESCRIPTION varchar(100),
	CONSTRAINT INVOICE_PK PRIMARY KEY (ID),
	CONSTRAINT INVOICE_FK FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE(ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4k
COLLATE=utf8mb4_0900_ai_ci;


insert into SAMPLE VALUES (1, "JHON", "This is the default user");
insert into INVOICE VALUES (1, "JACK INVOICE", "This is a test invoice");
insert into INVOICE_DETAIL VALUES (1, 1, 2, 10, "First item invoice");
insert into INVOICE_DETAIL VALUES (2, 1, 100, 10.20, "Second item invoice");

